trigger:
  - main

pool:
  name: 'Default'

steps:
  - script: |
      echo "Checking and changing permissions for cleanup"
      if [ -d "/home/azureuser/myagent/_work/1/s/C:/EyemanageLogs" ]; then
        sudo chmod -R 777 /home/azureuser/myagent/_work/1/s/C:/EyemanageLogs
      else
        echo "Directory /home/azureuser/myagent/_work/1/s/C:/EyemanageLogs does not exist"
      fi
    displayName: 'Change permissions for EyemanageLogs'

  - script: |
      echo "Cleaning up workspace"
      sudo rm -rf /home/azureuser/myagent/_work/1/s/*
      echo "Workspace cleaned"
    displayName: 'Clean up workspace'

  - checkout: self
    clean: true

  - script: |
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      echo "JAVA_HOME is set to: $JAVA_HOME"
      java -version
    displayName: 'Set and Verify Java installation'

  - task: Maven@3
    inputs:
      mavenPomFile: 'leafhub/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/leafhub/target'  # Path to your artifact(s)
      artifactName: 'Leafhub'  # Name of the artifact to publish

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/leafhub/target'
      Contents: '**/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - script: |
      # Find and kill the process occupying port 80
      sudo fuser -k 80/tcp || true

      # Start the Leafhub application as a nohup process
      sudo nohup java -jar $(Build.ArtifactStagingDirectory)/leafhub.jar > leafhub.log 2>&1 &
    displayName: 'Kill port 80 process and Start the Leafhub application'
